module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__16384[16384];
      struct Array16k {
        octet__16384 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
