module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__8388608[8388608];
      struct Array8m {
        octet__8388608 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
