module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__61440[61440];
      struct Array60k {
        octet__61440 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
