module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__4096[4096];
      struct Array4k {
        octet__4096 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
