module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__65536[65536];
      struct Array64k {
        octet__65536 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
