module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__32768[32768];
      struct Array32k {
        octet__32768 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
