module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__2097152[2097152];
      struct Array2m {
        octet__2097152 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
