module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__4194304[4194304];
      struct Array4m {
        octet__4194304 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
