module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__1024[1024];
      struct Array1k {
        octet__1024 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
