module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__1048576[1048576];
      struct Array1m {
        octet__1048576 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
