module performance_test {
  module msg {
    module __plugin__ {
      typedef octet octet__262144[262144];
      struct Array256k {
        octet__262144 array;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
