module performance_test {
  module msg {
    module __plugin__ {
      typedef sequence<octet, 4194304> bounded__octet__4194304;
      struct BoundedSequence4m {
        bounded__octet__4194304 bounded_sequence;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
