module performance_test {
  module msg {
    module __plugin__ {
      typedef sequence<octet, 4096> bounded__octet__4096;
      struct BoundedSequence4k {
        bounded__octet__4096 bounded_sequence;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
