module performance_test {
  module msg {
    module __plugin__ {
      typedef sequence<octet, 32768> bounded__octet__32768;
      struct BoundedSequence32k {
        bounded__octet__32768 bounded_sequence;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
