module performance_test {
  module msg {
    module __plugin__ {
      struct FixedTime {
        long sec;
        unsigned long nanosec;
        };
    }; // __plugin__
  }; // msg
}; // performance_test
