module performance_test {
  module msg {
    module __plugin__ {
      typedef char name_char__256[256];
      struct FixedPointField {
        name_char__256 name;
        unsigned long offset;
        octet datatype;
        unsigned long count;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
