#include "Time.idl"

module performance_test {
  module msg {
    module __plugin__ {
      typedef char char__256[256];
      struct Header {
        performance_test::msg::__plugin__::Time stamp;
        char__256 frame_id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
