#include "FixedPointField.idl"
#include "FixedHeader.idl"

module performance_test {
  module msg {
    module __plugin__ {
      typedef performance_test::msg::__plugin__::FixedPointField performance_test__msg__8m__PointField;
      typedef performance_test__msg__8m__PointField performance_test__msg__8m__PointField__8[8];
      typedef octet octet__pc__8388608[8388608];
      struct PointCloud8m {
        performance_test::msg::__plugin__::FixedHeader header;
        unsigned long height;
        unsigned long width;
        performance_test__msg__8m__PointField__8 fields;
        boolean is_bigendian;
        unsigned long point_step;
        unsigned long row_step;
        octet__pc__8388608 data;
        boolean is_dense;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
