#include "FixedHeader.idl"

module performance_test {
  module msg {
    module __plugin__ {
      struct Range {
        performance_test::msg::__plugin__::FixedHeader header;
        octet radiation_type;
        float field_of_view;
        float min_range;
        float max_range;
        float range;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
