module performance_test {
  module msg {
    module __plugin__ {
      typedef sequence<octet> unbounded__octet;
      struct UnboundedSequence {
        unbounded__octet unbounded_sequence;

        long long time;

        unsigned long long id;
      };
    }; // __plugin__
  }; // msg
}; // performance_test
